version: "3"

services:
  app:
    image: qdea/0501-shopify:latest
    container_name: app
    ports:
      - '8888:8080'
    networks:
      - mongo-network
    depends_on:
      - mongo-shop

  mongo-shop:
    restart: unless-stopped
    container_name: mongo-shop
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: shop
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - '27017:27017'
    networks:
      - mongo-network

networks:
  mongo-network:
    driver: bridge